stages:
- stage: Plan
  jobs:
  - job: A1
    steps: 
    - checkout: peab-pipeline
    - template: Terraform-Plan.yaml@peab-pipeline

- stage: Publish
  displayName: 'Publish Plan to Wiki'
  jobs:
  - template: Terraform-Publish-Plan-To-Wiki.yaml

- stage: Apply
  displayName: 'Terraform Apply'
  jobs:
  - template: Terraform-Apply.yaml