parameters:
  terraformRemoteStateFileResourceGroup: "tf-state-$(customer.shortname)-rg"
  terraformRemoteStateFileStorageAccount: "tfstate$(customer.shortname)sa"
  terraformRemoteStateFileBlobContainer: "tf-state-$(customer.shortname)-bc"
  terraformRemoteStateFile: "$(admin.azureDevOpsProject)-$(customer.shortname)-$(ENVIRONMENT).tfstate"
  terraformPath: "$(customer.shortname)-$(azure.enterpriseScaleSubscription)"
  
jobs:
- job: Publish
  displayName: 'Publish to Wiki'
  pool: 'az-pipeline-terraform-agent-pool'
  steps:
  - checkout: pipeline-terraform
    persistCredentials: true
  - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
    displayName: Install Terraform
    inputs:
      terraformVersion: $(terraform.version)
  - download: current
    artifact: 'tfplan'
  - script: |
     mkdir -p ${{ parameters.terraformRemoteStateFile }}/Terraform 
     tar -xzvf tfplan/${{parameters.terraformRemoteStateFile}}.tar.gz --directory ${{ parameters.terraformRemoteStateFile }}/Terraform
     echo "##[debug] Uncompress terraform directory done"
    displayName: 'Extract Artifact to ${{ parameters.terraformRemoteStateFile }}/Terraform'
    workingDirectory: '$(Pipeline.Workspace)'
  - script: |
     if [[ ! -f  .terraform/terraform.tfstate ]] ; then
        echo "##vso[task.logissue type=error] terraform.tfstate (.terraform/terraform.tfstate) is not here, aborting."
        exit
     else
       cat .terraform/terraform.tfstate
     fi
    workingDirectory: '$(Pipeline.Workspace)/${{ parameters.terraformRemoteStateFile }}/Terraform'
    displayName: 'Check for terraform.tfstate'
  - task: AzureCLI@2
    displayName: "Setup Authentication"
    inputs:
      azureSubscription: $(admin.azureEnvironmentConnection)
      scriptType: bash
      addSpnToEnvironment: true
      failOnStandardError: "true"
      scriptPath: scripts/set-variables.sh
    env:
      terraformBackendStorageAccount: ${{ parameters.terraformRemoteStateFileStorageAccount }}
      targetGitOrganization: $(admin.azureDevOpsOrganization)
      gitToken: $(git.token)
  - script: |
     mkdir -p ${{ parameters.terraformPath }}
     tar -xzvf tfplan/${{ parameters.terraformRemoteStateFile }}.tar.gz --directory ${{ parameters.terraformPath }}
     echo "##[debug] Compress terraform state file done"
    workingDirectory: '$(Pipeline.Workspace)'
  - task: Bash@3
    displayName: "Git Clone Wiki"
    continueOnError: 'true'
    inputs:
      filePath: scripts/clone-repo.sh
      workingDirectory: '$(Agent.WorkFolder)'
    env:
      gitToken: $(git.tokenAzureDevops)
      targetGitOrganization: $(admin.azureDevOpsOrganization)
      targetDir: $(admin.wikiProject)
      targetProject: $(settings.project)
      cloneUrl: $(settings.cloneSourceWiki)
      branchName: $(settings.branch)
  - task: Bash@3
    displayName: "'Terraform Show - Output'"
    inputs:
      filePath: scripts/terraform-init.sh
      workingDirectory: '$(Pipeline.Workspace)/${{ parameters.terraformPath }}'
    env:
      terraformBackendResourceGroup: ${{ parameters.terraformRemoteStateFileResourceGroup }}
      terraformBackendStorageAccount: ${{ parameters.terraformRemoteStateFileStorageAccount }}
      terraformBackendStorageContainer: ${{ parameters.terraformRemoteStateFileBlobContainer }}
      terraformRemoteStateFile: ${{ parameters.terraformRemoteStateFile }}
      ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID
      ARM_TENANT_ID: $ARM_TENANT_ID
      ARM_CLIENT_ID: $ARM_CLIENT_ID
      ARM_CLIENT_SECRET: $ARM_CLIENT_SECRET
      TF_VAR_GIT_TOKEN: $(git.token)
      terraformShowFlag: "True"
      terraformDestroy: "False"
  - task: Bash@3
    displayName: "Write Terraform Show to Wiki"
    inputs:
      failOnStandardError: "true"
      workingDirectory: $(Agent.WorkFolder)
      filePath: scripts/terraform-write-to-wiki.sh
    env:
      terraformDirectory: ${{ parameters.terraformPath }}
      wikiDirectory: $(settings.wikireleasedirectory)
  - task: Bash@3
    displayName: "Archive Old Builds"
    inputs:
      workingDirectory: $(Agent.WorkFolder)/wiki/$(settings.wikireleasedirectory)
      filePath: scripts/archive-old-builds.sh
    env:
      wikiDirectory: $(settings.wikireleasedirectory)
  - task: Bash@3
    displayName: "Git Push Wiki - View Link Here'"
    inputs:
      workingDirectory: '$(Agent.WorkFolder)/wiki'
      filePath: scripts/push-to-wiki.sh
    env:
      gitToken: $(git.tokenAzureDevops)
      targetGitOrganization: $(admin.azureDevOpsOrganization)
      targetDir: $(admin.wikiProject)
      targetProject: $(settings.project)
      wikiDirectory: $(settings.wikireleasedirectory)